// <auto-generated />
using System;
using FlashCardQuiz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashCardQuiz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("FlashCardQuiz.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("FlashCardQuiz.Models.CardStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Correct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wrong")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("CardStats");
                });

            modelBuilder.Entity("FlashCardQuiz.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("FlashCardQuiz.Models.QuizCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizCards");
                });

            modelBuilder.Entity("FlashCardQuiz.Models.QuizRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Correct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wrong")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizRuns");
                });

            modelBuilder.Entity("FlashCardQuiz.Models.CardStat", b =>
                {
                    b.HasOne("FlashCardQuiz.Models.Card", "Card")
                        .WithOne("CardStat")
                        .HasForeignKey("FlashCardQuiz.Models.CardStat", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("FlashCardQuiz.Models.QuizCard", b =>
                {
                    b.HasOne("FlashCardQuiz.Models.Quiz", null)
                        .WithMany("QuizCards")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashCardQuiz.Models.QuizRun", b =>
                {
                    b.HasOne("FlashCardQuiz.Models.Quiz", null)
                        .WithMany("QuizRuns")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashCardQuiz.Models.Card", b =>
                {
                    b.Navigation("CardStat");
                });

            modelBuilder.Entity("FlashCardQuiz.Models.Quiz", b =>
                {
                    b.Navigation("QuizCards");

                    b.Navigation("QuizRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
